### ISSUE TITLE
Text inside search box invisible on dark mode

### ISSUE THREAD

**Issue by mousetail** [robot-rumble/battle-viewer#24]
![Screenshot_20220624_130032](https://user-images.githubusercontent.com/12109031/175521725-fe39becb-c7fa-4414-b119-f54d24316472.png)

I typed things in but they are invisible. If I select the text I can see what I'm typing. Probably a simple styling issue.

**Comment by outkine** [comment]
Thank you for reporting! Fixed with https://github.com/robot-rumble/battle-viewer/commit/7608a5202c6335947d2908662eab37eaf5299d17
