### ISSUE TITLE
Show the total number of bots and total health anywhere

### ISSUE THREAD

**Issue by mousetail** [robot-rumble/battle-viewer#33]
When viewing a battle, I constantly need to count the number of bots to tell if I'm ahead or not. Especially I need to find the moment where the score if first different since that indicates one bot made a mistake.

Showing the total health would also be useful, as well as the change this turn.

Ugly mockup:

![afbeelding](https://github.com/robot-rumble/battle-viewer/assets/12109031/5049709a-31a7-435b-b332-06a63bfffb10)

**Comment by outkine** [comment]
Added info bar with https://github.com/robot-rumble/battle-viewer/commit/eb4c031018de392881883411d096b208bee4208f
![image](https://github.com/robot-rumble/battle-viewer/assets/25833343/5fd75ee8-e75f-4f4b-b23e-b0a5d34fb3a7)

**Comment by mousetail** [comment]
Very helpful, thanks
